- .github/ISSUE_TEMPLATE/feature.md
- src/main/java/com/nhnacademy/marketgg/auth/config/RedisConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/EmailRequestDto.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/SignupRequestDto.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/UsernameRequestDto.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRoles.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Provider.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Role.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Roles.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Token.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/DefaultAuthService.java
- src/main/resources/application.yml
- src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/DefaultAuthServiceTest.java
- #6
- 기존 회원가입 코드에 아이디, 이메일 중복 체크 기능추가했습니다.
- 해당 코드 기능 추가 및 테스트 코드 작성 완료 했습니다.
> Feature: 회원가입 아이디, 이메일 중복 체크 기능추가

- .github/PULL_REQUEST_TEMPLATE
- src/main/java/com/nhnacademy/marketgg/auth/config/WebConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/OAuth2Controller.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/SignupRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/GoogleProfile.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/TokenResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/exception/OAuthRequestFailException.java
- src/main/java/com/nhnacademy/marketgg/auth/oauth2/OAuthToken.java
- src/main/java/com/nhnacademy/marketgg/auth/oauth2/TokenRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/OAuth2Service.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
- src/main/resources/application.yml
- src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
- #10 
- 구글 소셜 로그인 진행
- 구글로 부터 Access Token 및 Refresh Token 받아올 수 있다
- 사용자 프로필 이름과 이메일만 받아와짐
- 사용자에게 토큰 발급 해야함
- 회원가입 해야함
> Feat: 구글 로그인 진행 #10

- src/main/java/com/nhnacademy/marketgg/auth/config/RedisConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/constant/Provider.java
- src/main/java/com/nhnacademy/marketgg/auth/constant/Roles.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRole.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Role.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
- #14 
- `config/RedisConfig` Javadoc 작성
- `config/WebSecurityConfig` Javadoc 작성 
- `controller/AuthController` Javadoc 작성
> Javadoc 작성

- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/EmailUseRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/ExistEmailResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/UseEmailResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/AuthRole.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/util/MailUtils.java
- src/main/java/com/nhnacademy/marketgg/auth/util/Status.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
> Feat: 회원가입

- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/SignUpRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/SignUpResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/UseEmailResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
- #6
- 회원가입시 추천인 적립금 제도를 위한 회원가입 기존 로직 추가 및 수정
> Refactor: 회원가입 추천인 로직 추가

- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthControllerAdvice.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/AuthUpdateRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/AuthWithDrawRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/EmailRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/AuthUpdateResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
- src/main/java/com/nhnacademy/marketgg/auth/exception/AuthNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/auth/exception/AuthWithDrawOverlapException.java
- src/main/java/com/nhnacademy/marketgg/auth/exception/UnAuthorizationException.java
- src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/SignUpControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpServiceTest.java
- #31 
- Entity 수정
- Comment: 모호한 UpdateRequest 클래스명 변경
> Fix: 회원탈퇴 로직 추가를 위해 Entity 필드 수정 및 Comment 반영

- src/main/java/com/nhnacademy/marketgg/auth/annotation/Token.java
- src/main/java/com/nhnacademy/marketgg/auth/aspect/TokenAspect.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/ExistEmailResponse.java
- #35 
- AOP 를 이용하여 토큰 검증 후 전달
- 토큰 검증 로직을 AOP 로 분리하여 중복코드 제거
> AOP 를 이용하여 토큰 검증 후 전달

- src/main/java/com/nhnacademy/marketgg/auth/AuthApplication.java
- src/main/java/com/nhnacademy/marketgg/auth/aspect/TokenAspect.java
- src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
- AOP 추가 후 정상작동 안되는 테스트 코드 수정
- AOP 수정
> Refactor: Test code 수정

- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/EmailRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/EmailUseRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/UseEmailResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRoleRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/RoleRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/service/SignUpService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
- #31
- Style 가이드 교정
- 회원탈퇴시 로그아웃 처리 로직 추가
> Style 가이드, 회원탈퇴 로직 변경

- src/main/java/com/nhnacademy/marketgg/auth/dto/response/UseEmailResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
> Fix: 코멘트 반영 수정

- src/main/java/com/nhnacademy/marketgg/auth/aspect/LogAspect.java
- src/main/java/com/nhnacademy/marketgg/auth/aspect/TokenAspect.java
- src/main/java/com/nhnacademy/marketgg/auth/config/RestTemplateConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/OAuth2Controller.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/LoginRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/MemberInfoRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/SignUpRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/AuthUpdateResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/MemberNameResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/OauthResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/exception/EmailOverlapException.java
- src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsService.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/AuthInfoControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoServiceTest.java
- Close #54 
- UUID 목록으로 회원 정보 목록 조회 
- QueryDsl in 을 사용하여 List 로 조건설정
Location: /auth/v1/info/names
> Shop의 회원의 UUID 로 회원의 이름, uuid  받아오기

- src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/MemberResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
- 로그아웃 오류 수정
- `logout().disable()`
- 중복 코드 수정
- 디버깅 위한 로그 추가
> Hotfix: 로그아웃 오류 수정

- .github/workflows/maven.yml
- pom.xml
- src/main/java/com/nhnacademy/marketgg/auth/config/SwaggerConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/config/WebSecurityConfig.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/common/CommonResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
- src/main/java/springfox/documentation/spring/web/plugins/WebMvcRequestHandlerProvider.java
> Swagger 적용

- src/main/java/com/nhnacademy/marketgg/auth/dto/response/SignUpResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/exception/AuthNotFoundException.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
- src/test/java/com/nhnacademy/marketgg/auth/AuthApplicationTests.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/AuthControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/LoginTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpServiceTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsServiceTest.java
- #73 
- 이슈 내용 참조
- 회원가입 Service 테스트 코드 고도화
> Client -> GateWay -> Shop -> Auth 서버로 회원가입 로직 수정 예정
> 회원가입 이메일 인증 추가

- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
> Refactor: 토큰 갱신 오류 수정

- .github/workflows/main.yml
- .github/workflows/maven.yml
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthController.java
- 배포 방식 변경
- Develop 브랜치에 Push 시 빌드만 수행
- Main 브랜치에 Push 시 빌드 -> SonarQube 테스트 ->  auth 에 배포
> Chore: 배포 수정

- src/main/java/com/nhnacademy/marketgg/auth/jwt/TokenUtils.java
- src/main/resources/log4j2-prod.xml
> Chore: Prod Log 설정 추가

- lombok.config
- src/main/java/com/nhnacademy/marketgg/auth/aop/TokenAspect.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/AuthWithDrawRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/MemberUpdateRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/UuidTokenResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
> 회원 수정, 삭제 Final

- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultSignUpService.java
> Fix: 추천인 uuid 반환 수정

- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/Payload.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/request/DefaultPageRequest.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/AdminMemberResponse.java
- src/main/java/com/nhnacademy/marketgg/auth/dto/response/common/PageEntity.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/auth/AuthRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/auth/AuthRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/authrole/AuthRoleRepository.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/role/RoleRepositoryCustom.java
- src/main/java/com/nhnacademy/marketgg/auth/repository/role/RoleRepositoryImpl.java
- src/main/java/com/nhnacademy/marketgg/auth/service/AuthInfoService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoService.java
- src/test/java/com/nhnacademy/marketgg/auth/controller/AuthInfoControllerTest.java
- src/test/java/com/nhnacademy/marketgg/auth/repository/AuthRepositoryTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthInfoServiceTest.java
- Close #85 
- 관리자 회원 목록 조회
- 관리자 회원 목록 조회 API 개발
- 테스트
> 관리자 회원 목록 조회 API 개발

- src/main/java/com/nhnacademy/marketgg/auth/aop/advice/AuthControllerAdvice.java
- src/main/java/com/nhnacademy/marketgg/auth/aop/advice/ExceptionMessageCode.java
- src/main/java/com/nhnacademy/marketgg/auth/controller/AuthInfoController.java
- src/main/java/com/nhnacademy/marketgg/auth/entity/Auth.java
- src/main/java/com/nhnacademy/marketgg/auth/filter/JwtAuthenticationFilter.java
- src/main/java/com/nhnacademy/marketgg/auth/jwt/CustomUser.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsService.java
- src/main/java/com/nhnacademy/marketgg/auth/service/impl/GoogleLoginService.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultAuthServiceTest.java
- src/test/java/com/nhnacademy/marketgg/auth/service/impl/DefaultUserDetailsServiceTest.java
> Refactor: 탈퇴 회원 관리
